# NAME: Belle Lerdworatawee
# EMAIL: bellelee@g.ucla.edu
# ID: 105375663

default: lab3b.py
	rm -f lab3b
	ln lab3b.py lab3b
	chmod 777 lab3b

clean:
	rm -rf lab3b *.tar.gz

dist: default
	tar -czvf lab3b-105375663.tar.gz lab3b.py Makefile README
